name: PostgreSQLAdapter test
on: push

jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: node:10.18-jessie

    steps:
    env:
        DB_DATABASE: mysql_test
        DB_USER: mysql
        DB_PASSWORD: mysql
  - name: Set up MySQL
    run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
  - uses: actions/checkout@v2
  - uses: julia-actions/setup-julia@latest
    with:
      version: '1.6.4'
      arch: 'x64'
  - uses: julia-actions/julia-buildpkg@master
  - name: Install SearchLight and SearchLightMySQL
    run: |
      pwd
      julia -e 'using Pkg; Pkg.add(url="https://github.com/FrankUrbach/SearchLight.jl.git")'
      julia -e 'using Pkg; Pkg.add(url="https://github.com/FrankUrbach/SearchLightMySQL.jl.git")'
      julia -e 'import Pkg; Pkg.add("SafeTestsets")'
      julia -e 'cd(joinpath(pwd(),"test"))'
      julia -e 'using Pkg; Pkg.activate(".")'
      julia -e 'using Pkg; Pkg.resolve()'
    shell: bash
  - uses: julia-actions/julia-runtest@master
