name: PostgreSQLAdapter test
on: push

jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: node:10.18-jessie

    steps:
      - name: Set up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
            container port: 3306 # Optional, default value is 3306. The port of container
            character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
            collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
            mysql database: 'mysql_test' # Optional, default value is "test". The specified database which will be create
            mysql root password: 'mysql' # Required if "mysql user" is empty, default is empty. The root superuser password
            mysql user: 'mysql' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
            mysql password: 'mysql' # Required if "mysql user" exists. The password for the "mysql user"

      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.6.4'
          arch: 'x64'
      - uses: julia-actions/julia-buildpkg@master
      - name: Install SearchLight and SearchLightMySQL
        run: |
          pwd
          julia -e 'using Pkg; Pkg.add(url="https://github.com/FrankUrbach/SearchLight.jl.git")'
          julia -e 'using Pkg; Pkg.add(url="https://github.com/FrankUrbach/SearchLightMySQL.jl.git")'
        shell: bash
      - uses: julia-actions/julia-runtest@master
